services:
  - type: web
    name: effortless-eighty
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0

